app = "movex-backend"
primary_region = "gru"  # São Paulo (Guarulhos)
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"
  DEBUG = "False"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]
  force_https = true

[[services.tcp_checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "1s"