services:
  - type: web
    name: movex-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn movex.asgi:application -k uvicorn.workers.UvicornWorker -c gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: '.onrender.com,127.0.0.1,localhost'
    healthCheckPath: /api/usuarios/