# Generated by Django 5.1.7 on 2025-03-27 11:59

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('tipo_usuario', models.CharField(choices=[('PASSAGEIRO', 'Passageiro'), ('MOTORISTA', 'Motorista'), ('ADMINISTRADOR', 'Administrador'), ('DIRETOR', 'Diretor')], default='PASSAGEIRO', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='passageiros/')),
                ('avaliacao_media', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Passageiro',
                'verbose_name_plural': 'Passageiros',
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('cnh', models.CharField(max_length=20, unique=True)),
                ('categoria_cnh', models.CharField(max_length=5)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='motoristas/')),
                ('avaliacao_media', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3)),
                ('modelo_veiculo', models.CharField(max_length=100)),
                ('ano_veiculo', models.IntegerField()),
                ('placa_veiculo', models.CharField(max_length=10)),
                ('cor_veiculo', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('OCUPADO', 'Ocupado'), ('OFFLINE', 'Offline'), ('INATIVO', 'Inativo')], default='OFFLINE', max_length=20)),
                ('esta_disponivel', models.BooleanField(default=False)),
                ('ultima_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ultima_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ultima_atualizacao_localizacao', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motorista', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
            },
        ),
    ]
