# Generated by Django 5.1.7 on 2025-04-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='foto_perfil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='foto_perfil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
