# Generated by Django 5.1.7 on 2025-04-18 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_convert_image_fields_to_char_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='motoristas/'),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='passageiros/'),
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('plataforma', models.CharField(default='expo', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='push_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Push',
                'verbose_name_plural': 'Tokens Push',
            },
        ),
    ]
