# Generated by Django 5.1.7 on 2025-03-27 11:59

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('MOTORISTA_CHEGOU', 'Motorista Chegou'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('data_solicitacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_aceite', models.DateTimeField(blank=True, null=True)),
                ('data_chegada_motorista', models.DateTimeField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('origem_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('origem_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('origem_descricao', models.CharField(default='Local de origem', max_length=255)),
                ('destino_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destino_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destino_descricao', models.CharField(default='Local de destino', max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('distancia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('tempo_estimado', models.IntegerField(default=0)),
                ('info_adicional_passageiro', models.TextField(blank=True, null=True)),
                ('contato_alternativo', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True, null=True)),
                ('cancelada_por_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('cancelada_por_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('motorista_temporariamente_desconectado', models.BooleanField(default=False)),
                ('avaliacao_motorista', models.IntegerField(blank=True, null=True)),
                ('avaliacao_passageiro', models.IntegerField(blank=True, null=True)),
                ('comentario_motorista', models.TextField(blank=True, null=True)),
                ('comentario_passageiro', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Corrida',
                'verbose_name_plural': 'Corridas',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
