# Generated by Django 5.1.7 on 2025-04-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='data_avaliacao_motorista',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='data_avaliacao_passageiro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
