# Generated by Django 5.1.7 on 2025-04-12 14:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0003_corrida_data_avaliacao_motorista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_remetente', models.CharField(choices=[('PASSAGEIRO', 'Passageiro'), ('MOTORISTA', 'Motorista')], max_length=20)),
                ('conteudo', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='corridas.corrida')),
            ],
            options={
                'ordering': ['data_envio'],
            },
        ),
    ]
