# Generated by Django 5.1.7 on 2025-04-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0004_mensagemchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemchat',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mensagemchat',
            name='lida',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='mensagemchat',
            name='tipo_remetente',
            field=models.CharField(choices=[('PASSAGEIRO', 'Passageiro'), ('MOTORISTA', 'Motorista')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='mensagemchat',
            index=models.Index(fields=['corrida', 'tipo_remetente'], name='corridas_me_corrida_1bb5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagemchat',
            index=models.Index(fields=['corrida', 'lida'], name='corridas_me_corrida_b75f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagemchat',
            index=models.Index(fields=['corrida', 'data_envio'], name='corridas_me_corrida_57865d_idx'),
        ),
    ]
